const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const bible = fs.readFileSync(path.join(root, 'bible.html'), 'utf8');
const sw = fs.readFileSync(path.join(root, 'sw.js'), 'utf8');

assert.match(bible, /var APP_VERSION = '3\.0\.0';/);
assert.match(sw, /var CACHE_NAME = 'bible-v3\.0\.0';/);
assert.match(bible, /id="app-version"/);
assert.match(bible, /Version <span id="app-version">3\.0\.0<\/span>/);

assert.match(bible, /id="font-size-slider"/);
assert.match(bible, /var FONT_STEPS = \[16, 18, 20, 22, 24\];/);
assert.match(bible, /--reader-font-size/);
assert.match(bible, /bible_font_step/);
assert.match(bible, /class="font-slider-track"/);
assert.match(bible, /class="font-slider-ticks"/);
assert.match(bible, /<span style="left: 0%;">16<\/span>[\s\S]*<span style="left: 25%;">18<\/span>[\s\S]*<span style="left: 50%;">20<\/span>[\s\S]*<span style="left: 75%;">22<\/span>[\s\S]*<span style="left: 100%;">24<\/span>/);

assert.match(bible, /\.fab-panel\.open \{ display: flex; \}/);
assert.match(bible, /position: absolute;/);
assert.match(bible, /bottom: calc\(100% \+ 8px\);/);
assert.match(bible, /width: min\(360px, calc\(100vw - 24px\)\);/);
assert.match(bible, /max-height: calc\(100dvh - 96px - env\(safe-area-inset-bottom, 0px\)\);/);
assert.match(bible, /\.fab-history-menu \{ flex: 1 1 auto; min-height: 0; overflow-y: auto; \}/);
assert.doesNotMatch(bible, /width: 100vw;/);
assert.doesNotMatch(bible, /height: 100dvh;/);
assert.doesNotMatch(bible, /\.fab-root:has\(\.fab-panel\.open\) \.fab-main/);
assert.doesNotMatch(bible, /id="fab-close"/);
assert.doesNotMatch(bible, /fabClose\.addEventListener\('click'/);

assert.match(bible, /id="fn-verse"/);
assert.match(bible, /function showVersePickerView\(bookName, chapterNum\)/);
assert.match(bible, /view: 'verse-picker'/);
assert.match(bible, /fnVerse\.textContent = activeVerse \? activeVerse : '1';/);
assert.doesNotMatch(bible, /fnVerse\.textContent = activeVerse \? activeVerse : 'Verse';/);
assert.doesNotMatch(bible, /fnVerse\.textContent = activeVerse \? ':' \+ activeVerse : 'Verse';/);
assert.match(bible, /setActiveVerse\(keys\[0\], false\)/);
assert.match(bible, /var verseChaseFrame = null;/);
assert.match(bible, /var verseChaseVelocity = 0;/);
assert.match(bible, /var verseChaseTarget = null;/);
assert.match(bible, /var verseChaseLastTs = null;/);
assert.match(bible, /function desiredVerseScrollTop\(target\)/);
assert.match(bible, /function shouldReduceVerseMotion\(\)/);
assert.match(bible, /function stopVerseChase\(\)/);
assert.match(bible, /function releaseVerseChaseForFreeScroll\(\)/);
assert.match(bible, /function setVerseChaseTarget\(target\)/);
assert.match(bible, /function stepVerseChase\(ts\)/);
assert.match(bible, /function scrollVerseToCenter\(target\)/);
assert.match(bible, /if \(verseChaseTarget\) return;/);
assert.match(bible, /Math\.min\(maxTop, Math\.max\(0, desiredTop\)\)/);
assert.match(bible, /var pull = Math\.min\(0\.085, Math\.max\(0\.018, Math\.abs\(distance\) \/ 9000\)\);/);
assert.match(bible, /var damping = Math\.abs\(distance\) < 80 \? 0\.72 : 0\.88;/);
assert.match(bible, /var maxSpeed = Math\.min\(90, Math\.max\(10, Math\.abs\(distance\) \* 0\.18\)\);/);
assert.match(bible, /if \(Math\.abs\(distance\) < 0\.7 && Math\.abs\(verseChaseVelocity\) < 0\.7\)/);
assert.match(bible, /verseChaseFrame = requestAnimationFrame\(stepVerseChase\);/);
assert.match(bible, /setVerseChaseTarget\(target\);/);
assert.doesNotMatch(bible, /function verseEaseLateBrake/);
assert.doesNotMatch(bible, /var duration = Math\.min\(780/);
assert.match(bible, /\.verse-edge-spacer/);
assert.match(bible, /\.verse-head-spacer/);
assert.match(bible, /\.verse-tail-spacer/);
assert.match(bible, /headSpacer\.className = 'verse-edge-spacer verse-head-spacer';/);
assert.match(bible, /tailSpacer\.className = 'verse-edge-spacer verse-tail-spacer';/);
assert.doesNotMatch(bible, /ACTIVE_VERSE_SETTLE_MS/);
assert.doesNotMatch(bible, /activeVerseTimer/);
assert.doesNotMatch(bible, /function scheduleActiveVerseCenter/);
assert.doesNotMatch(bible, /scheduleActiveVerseCenter\(/);
assert.doesNotMatch(bible, /function isNearScrollBottom\(\)/);
assert.doesNotMatch(bible, /scrollIntoView\(\{ behavior: 'smooth', block: 'center' \}\)/);
assert.match(bible, /\.verse\.active/);

assert.match(bible, /--verse-num: #555;/);
assert.match(bible, /--verse-num: #b8b8b8;/);

assert.match(bible, /document\.addEventListener\('keydown', handleBibleKeyboardNavigation\);/);
assert.match(bible, /viewEl\.addEventListener\('wheel', releaseVerseChaseForFreeScroll, \{ passive: true \}\);/);
assert.match(bible, /function handleBibleKeyboardNavigation\(e\)/);
assert.match(bible, /function shouldIgnoreBibleShortcut\(e\)/);
assert.match(bible, /tag === 'INPUT' \|\| tag === 'TEXTAREA' \|\| tag === 'SELECT'/);
assert.match(bible, /e\.metaKey \|\| e\.ctrlKey \|\| e\.altKey/);
assert.match(bible, /function handleSelectionArrowKey\(key\)/);
assert.match(bible, /function focusClosestGridItem\(items, current, key\)/);
assert.match(bible, /getBoundingClientRect\(\)/);
assert.match(bible, /candidate\.score = directionalDistance\(currentRect, rect, key\);/);
assert.match(bible, /function handleSelectionEnterKey\(\)/);
assert.match(bible, /document\.activeElement\.click\(\);/);
assert.match(bible, /function handleReadingEnterKey\(\)/);
assert.match(bible, /var active = viewInner\.querySelector\('\.verse\.active'\);/);
assert.match(bible, /var noteButtons = active\.querySelectorAll\('\.footnote-toggle'\);/);
assert.match(bible, /var noteBodies = active\.querySelectorAll\('\.footnote-body'\);/);
assert.match(bible, /noteBodies\[i\]\.className = shouldOpen \? 'footnote-body visible' : 'footnote-body';/);
assert.match(bible, /noteButtons\[i\]\.className = shouldOpen \? 'footnote-toggle open' : 'footnote-toggle';/);
assert.match(bible, /function handleKeyboardBack\(\)/);
assert.match(bible, /if \(uiView === 'verse-picker'\) \{ showChaptersView\(navBook\); return true; \}/);
assert.match(bible, /if \(uiView === 'chapters'\) \{ showBooksView\(\); return true; \}/);
assert.match(bible, /if \(uiView === 'verses'\) \{ showVersePickerView\(navBook, navChapter\); return true; \}/);
assert.match(bible, /function handleReadingArrowKey\(key\)/);
assert.match(bible, /if \(key === 'ArrowLeft'\) return showAdjacentChapter\(-1\);/);
assert.match(bible, /if \(key === 'ArrowRight'\) return showAdjacentChapter\(1\);/);
assert.match(bible, /if \(key === 'ArrowUp'\) return showAdjacentVerse\(-1\);/);
assert.match(bible, /if \(key === 'ArrowDown'\) return showAdjacentVerse\(1\);/);
assert.match(bible, /function showAdjacentChapter\(direction\)/);
assert.match(bible, /direction < 0 \? prevChapterNav\(navBook, navChapter\) : nextChapterNav\(navBook, navChapter\)/);
assert.match(bible, /function showAdjacentVerse\(direction\)/);
assert.match(bible, /scrollVerseToCenter\(target\);/);
assert.match(bible, /if \(key === 'Enter'\) handled = uiView === 'verses' \? handleReadingEnterKey\(\) : handleSelectionEnterKey\(\);/);
assert.match(bible, /if \(key === 'Escape' \|\| key === 'Backspace' \|\| key === 'Delete'\) handled = handleKeyboardBack\(\);/);

assert.match(bible, /var CHAPTER_CROSSFADE_MS = 520;/);
assert.match(bible, /var chapterCrossfadeTimer = null;/);
assert.match(bible, /\.view-inner\.chapter-transition-retiring/);
assert.match(bible, /\.view-inner\.chapter-transition-ready \{ opacity: 0; transition: none; \}/);
assert.match(bible, /\.view-inner\.chapter-transition-ready\.chapter-transition-in \{ opacity: 1; transition: opacity 520ms ease-in-out; \}/);
assert.match(bible, /transition: opacity 520ms ease-in-out/);
assert.match(bible, /@media \(prefers-reduced-motion: reduce\) \{[\s\S]*?\.view-inner \{[\s\S]*?transition: none;/);
assert.match(bible, /function clearChapterCrossfadeTimer\(\)/);
assert.match(bible, /window\.clearTimeout\(chapterCrossfadeTimer\);/);
assert.match(bible, /function clearRetiringChapterViews\(\)/);
assert.match(bible, /viewEl\.querySelectorAll\('\.chapter-transition-retiring'\)/);
assert.match(bible, /function showVersesViewWithTransition\(bookName, chapterNum, scrollToVerse\)/);
assert.match(bible, /var retiring = viewInner\.cloneNode\(true\);/);
assert.match(bible, /retiring\.className = 'view-inner chapter-transition-retiring';/);
assert.match(bible, /retiring\.style\.transform = 'translateY\(-' \+ viewEl\.scrollTop \+ 'px\)';/);
assert.match(bible, /viewInner\.classList\.add\('chapter-transition-ready'\);/);
assert.match(bible, /showVersesView\(bookName, chapterNum, scrollToVerse\);/);
assert.match(bible, /void viewInner\.offsetWidth;/);
assert.match(bible, /viewInner\.classList\.add\('chapter-transition-in'\);/);
assert.match(bible, /viewInner\.classList\.remove\('chapter-transition-ready', 'chapter-transition-in'\);/);
assert.match(bible, /chapterCrossfadeTimer = window\.setTimeout\(function \(\) \{/);
assert.match(bible, /showVersesViewWithTransition\(next\.book, next\.chapter\);/);
assert.match(bible, /if \(p\) showVersesViewWithTransition\(p\.book, p\.chapter\);/);
assert.match(bible, /if \(n\) showVersesViewWithTransition\(n\.book, n\.chapter\);/);

assert.match(bible, /getThemeMode: function \(\) \{/);
assert.match(bible, /return this\._get\('bible_theme_mode', 'light'\);/);
assert.match(bible, /setThemeMode: function \(mode\) \{/);
assert.match(bible, /mode === 'dark' \|\| mode === 'auto' \? mode : 'light'/);
assert.match(bible, /function preferredDarkQuery\(\)/);
assert.match(bible, /window\.matchMedia\('\(prefers-color-scheme: dark\)'\)/);
assert.match(bible, /function resolveThemeMode\(mode\)/);
assert.match(bible, /if \(mode !== 'auto'\) return mode === 'dark';/);
assert.match(bible, /return preferredDarkQuery\(\) \? preferredDarkQuery\(\)\.matches : false;/);
assert.match(bible, /function applyThemeMode\(mode\)/);
assert.match(bible, /State\.setThemeMode\(mode\);/);
assert.match(bible, /document\.documentElement\.classList\.toggle\('dark', resolveThemeMode\(mode\)\);/);
assert.match(bible, /class="theme-mode-wrap"/);
assert.match(bible, /class="theme-mode-control" role="group" aria-label="Color scheme"/);
assert.match(bible, /data-theme-mode="light" aria-pressed="true">Light<\/button>/);
assert.match(bible, /data-theme-mode="dark" aria-pressed="false">Dark<\/button>/);
assert.match(bible, /data-theme-mode="auto" aria-pressed="false">Auto<\/button>/);
assert.match(bible, /var themeModeButtons = Array\.prototype\.slice\.call\(document\.querySelectorAll\('\[data-theme-mode\]'\)\);/);
assert.match(bible, /button\.classList\.toggle\('active', selected\);/);
assert.match(bible, /button\.setAttribute\('aria-pressed', selected \? 'true' : 'false'\);/);
assert.match(bible, /themeModeButtons\.forEach\(function \(button\) \{/);
assert.match(bible, /applyThemeMode\(button\.getAttribute\('data-theme-mode'\)\);/);
assert.match(bible, /applyThemeMode\(State\.getThemeMode\(\)\);/);
assert.match(bible, /themeQuery\.addEventListener\('change', onThemeQueryChange\);/);
assert.match(bible, /themeQuery\.addListener\(function \(\) \{/);
assert.match(bible, /if \(State\.getThemeMode\(\) === 'auto'\) applyThemeMode\('auto'\);/);
assert.doesNotMatch(bible, /function nextThemeMode\(mode\)/);
assert.doesNotMatch(bible, /id="dd-dark"/);
assert.doesNotMatch(bible, /ddDarkVal/);
assert.doesNotMatch(bible, /State\.getDark\(\)/);
assert.doesNotMatch(bible, /State\.setDark/);
