const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const bible = fs.readFileSync(path.join(root, 'bible.html'), 'utf8');
const sw = fs.readFileSync(path.join(root, 'sw.js'), 'utf8');
const marqueeDeclarations = [...bible.matchAll(/([^{}]+)\{([^{}]*)\}/g)]
  .filter(([, selector]) => /\.marquee-/.test(selector))
  .map(([, , declarations]) => declarations)
  .join('\n');

assert.match(bible, /var APP_VERSION = '3\.3\.3';/);
assert.match(sw, /var CACHE_NAME = 'bible-v3\.2\.0';/);
assert.match(bible, /id="app-version"/);
assert.match(bible, /<span class="app-version-label">Version <span id="app-version">3\.3\.3<\/span><\/span><span class="app-version-separator">\|<\/span><span id="footer-status" class="app-version-status" role="status" aria-live="polite">Signed out<\/span><span id="footer-signout-separator" class="app-version-separator" hidden>\|<\/span><button type="button" id="footer-signout" class="dd-signout-button" hidden>Sign Out<\/button>/);

assert.match(bible, /--oneui-font:/);
assert.match(bible, /--surface: #ffffff;/);
assert.match(bible, /--surface-hi: #eef3f9;/);
assert.match(bible, /--accent: #0b63ce;/);
assert.match(bible, /--accent-glow: rgba\(11,99,206,\.22\);/);
assert.match(bible, /--verse-bg: var\(--bg2\);/);
assert.match(bible, /--verse-active-border: color-mix\(in srgb, var\(--accent\) 60%, var\(--selection-fill\)\);/);
assert.match(bible, /--verse-highlight: var\(--hover-bg\);/);
assert.match(bible, /:root \{[\s\S]*--selection-fill: #f4f7fb;/);
assert.match(bible, /html\.dark \{[\s\S]*--selection-fill: #111722;/);
assert.match(bible, /--float-nav-bg: color-mix\(in srgb, var\(--surface-hi\) 92%, transparent\);/);
assert.match(bible, /--float-nav-shadow: 0 8px 22px color-mix\(in srgb, var\(--fg\) 14%, transparent\);/);
assert.match(bible, /--ui-radius: 20px;/);
assert.match(bible, /--ui-grid-gap: 8px;/);
assert.match(bible, /--ui-view-pad: 12px;/);
assert.match(bible, /--oneui-radius: var\(--ui-radius\);/);
assert.match(bible, /--oneui-inset-radius: calc\(var\(--oneui-radius\) - max\(4px, calc\(var\(--display-panel-padding\) \/ 3\)\)\);/);
assert.match(bible, /--radius-xs: min\(var\(--oneui-inset-radius\), calc\(var\(--ui-radius\) \* \.8\)\);/);
assert.match(bible, /--radius-sm: var\(--oneui-radius\);/);
assert.match(bible, /--radius-md: var\(--oneui-radius\);/);
assert.match(bible, /--bottom-chrome-clearance: calc\(var\(--display-control-height\) \+ \(var\(--display-nav-padding\) \* 2\) \+ 20px\);/);
assert.match(bible, /html\.dark \{[\s\S]*--surface: #171c28;/);
assert.match(bible, /html\.dark \{[\s\S]*--accent: #5b9bf4;/);
assert.doesNotMatch(bible, /html\.dark \{[^}]*--float-nav-bg:/);
assert.doesNotMatch(bible, /html\.dark \{[^}]*--float-nav-shadow:/);
assert.match(bible, /font-family: var\(--oneui-font\);/);
assert.match(bible, /body \{[\s\S]*white-space: nowrap;/);
assert.match(bible, /backdrop-filter: var\(--hdr-blur\);/);
assert.match(bible, /background: var\(--card-bg\); border: var\(--card-border\); border-radius: var\(--radius-sm\);/);
assert.match(bible, /button,\n  \.dd-item,\n  \.book-btn,\n  \.chapter-btn \{[\s\S]*transition-property: background, border-color, box-shadow, color, transform;[\s\S]*transition-duration: 180ms, 180ms, 180ms, 180ms, 120ms;/);
assert.match(bible, /button:active,\n  \.dd-item:active,\n  \.book-btn:active,\n  \.chapter-btn:active \{[\s\S]*transform: scale\(\.975\);[\s\S]*transition-duration: 80ms;/);
assert.match(bible, /\.verse \{[\s\S]*border-radius: var\(--verse-radius\);[\s\S]*border: 1px solid transparent;[\s\S]*transition-property: background, border-color, box-shadow, padding, border-width;[\s\S]*transition-duration: 0\.2s;[\s\S]*background: transparent;[\s\S]*white-space: normal;[\s\S]*overflow-wrap: anywhere;/);
assert.match(bible, /\.verse\.active \{[^}]*border-color: var\(--verse-active-border\);[^}]*border-width: 1px;/);
assert.match(bible, /\.verse\.active \{[\s\S]*background: var\(--selection-fill\);/);
assert.doesNotMatch(bible, /\.verse\.active \{[^}]*box-shadow\s*:/);
assert.match(bible, /\.verse:focus-visible \{[^}]*outline: 2px solid var\(--verse-active-border\);[^}]*outline-offset: 2px;/);
assert.match(bible, /\.verse\.footnotes-open \{[\s\S]*padding: var\(--verse-open-pad-y\) var\(--verse-open-pad-x\);/);
assert.doesNotMatch(bible, /\.verse\.footnotes-open \{[^}]*(?:background|border-color|box-shadow):/);
assert.match(bible, /\.book-btn \{[\s\S]*background: var\(--selection-fill\);/);
assert.match(bible, /\.chapter-btn \{[\s\S]*background: var\(--selection-fill\);/);
assert.match(bible, /\.footnote-toggle \{[\s\S]*border-radius: var\(--radius-pill\);[\s\S]*transition-property: background, color, border-color, box-shadow;[\s\S]*transition-duration: 0\.16s;/);
assert.match(bible, /\.footnote-body \{[\s\S]*margin: 0 0 0 var\(--footnote-indent\);[\s\S]*max-height: 0;[\s\S]*opacity: 0;[\s\S]*overflow: hidden;[\s\S]*padding: 0 var\(--footnote-pad-x\);[\s\S]*background: var\(--note-bg\);[\s\S]*border: 0 solid color-mix\(in srgb, var\(--note-border\) 45%, transparent\);[\s\S]*border-left-width: 0;[\s\S]*border-radius: var\(--footnote-radius\);[\s\S]*transition-property: opacity, max-height, margin, padding, border-width, transform;[\s\S]*transition-duration: 180ms, 220ms, 220ms, 220ms, 220ms, 220ms;/);
assert.match(bible, /\.footnote-body\.visible \{[\s\S]*margin: var\(--footnote-visible-margin-top\) 0 var\(--footnote-visible-margin-bottom\) var\(--footnote-indent\);[\s\S]*max-height: 40vh;[\s\S]*opacity: 1;[\s\S]*padding: var\(--footnote-visible-pad-y\) var\(--footnote-visible-pad-x\);[\s\S]*border-width: 1px;[\s\S]*border-left-width: 4px;[\s\S]*transform: translateY\(0\);/);

assert.doesNotMatch(bible, /id="font-size-slider"/);
assert.match(bible, /var BASE_UI_GEOMETRY = \{[\s\S]*controlHeight: 48,[\s\S]*iconSize: 48,[\s\S]*viewPad: 12[\s\S]*\};/);
assert.match(bible, /function uiGeometryForScale\(scale\) \{[\s\S]*Math\.min\(scale, 100\) \/ 100;[\s\S]*BASE_UI_GEOMETRY/);
assert.match(bible, /--reader-font-size/);
assert.match(bible, /--display-control-font-size: var\(--text-20\);/);
assert.match(bible, /--display-control-height: 48px;/);
assert.match(bible, /--display-segment-height: 48px;/);
assert.match(bible, /document\.documentElement\.style\.setProperty\('--display-control-height', uiGeometry\.controlHeight \+ 'px'\);/);
assert.match(bible, /document\.documentElement\.style\.setProperty\('--ui-view-pad', uiGeometry\.viewPad \+ 'px'\);/);
assert.match(bible, /bible_font_step/);
assert.doesNotMatch(bible, /class="font-slider-track"/);
assert.doesNotMatch(bible, /class="font-slider-ticks"/);
assert.doesNotMatch(bible, /\.font-slider \{/);
assert.doesNotMatch(bible, /Font Size/);

assert.match(bible, /\.fab-panel \{[\s\S]*display: flex;[\s\S]*position: fixed;[\s\S]*right: var\(--display-viewport-inset\);[\s\S]*bottom: var\(--bottom-chrome-clearance\);[\s\S]*width: min\(var\(--display-panel-width\), calc\(100vw - \(var\(--display-viewport-inset\) \* 2\)\)\);[\s\S]*max-height: calc\(100dvh - var\(--bottom-chrome-clearance\) - var\(--display-viewport-inset\)\);[\s\S]*overflow-y: auto;[\s\S]*overscroll-behavior: contain;[\s\S]*gap: var\(--display-panel-gap\);[\s\S]*padding: var\(--display-panel-padding\);[\s\S]*transform: translateY\(var\(--display-panel-motion-offset\)\);[\s\S]*background: var\(--float-nav-bg\);[\s\S]*border: var\(--card-border\);[\s\S]*border-radius: var\(--radius-md\);[\s\S]*box-shadow: var\(--float-nav-shadow\);[\s\S]*backdrop-filter: var\(--hdr-blur\);[\s\S]*-webkit-backdrop-filter: var\(--hdr-blur\);[\s\S]*isolation: isolate;[\s\S]*transition-property: opacity, transform, visibility;[\s\S]*transition-duration: 180ms, 180ms, 0s;[\s\S]*transition-delay: 0s, 0s, 180ms;/);
assert.match(bible, /\.fab-panel\.open \{[\s\S]*opacity: 1;[\s\S]*visibility: visible;[\s\S]*pointer-events: auto;[\s\S]*transition-property: opacity, transform, visibility;[\s\S]*transition-duration: 180ms, 180ms, 0s;/);
assert.doesNotMatch(bible, /\.fab-panel::before/);
assert.match(bible, /\.fab-card \{[\s\S]*margin: 0;[\s\S]*padding: var\(--display-panel-padding\);[\s\S]*border-radius: var\(--radius-sm\);[\s\S]*background: var\(--card-bg\);[\s\S]*border: var\(--card-border\);/);
assert.match(bible, /\.fab-card-title \{[\s\S]*font-size: var\(--text-14\);[\s\S]*padding: 0 2px 8px;[\s\S]*white-space: nowrap; overflow: hidden;/);
assert.match(bible, /\.profile-card \{[\s\S]*--profile-photo-height: calc\(var\(--display-control-height\) \+ \(var\(--display-panel-padding\) \* 4\)\);[\s\S]*position: relative;[\s\S]*overflow: hidden;[\s\S]*min-height: max\(24px, min\(92px,[\s\S]*flex-shrink: 1;[\s\S]*padding: 0 var\(--display-panel-padding\) 0 0;/);
assert.match(bible, /\.profile-card\.signed-out \{[\s\S]*overflow: visible;[\s\S]*min-height: 0;[\s\S]*padding: 0;/);
assert.doesNotMatch(bible, /\.profile-card \{[^}]*padding-left: 132px;/);
assert.doesNotMatch(bible, /\.profile-card::after/);
assert.doesNotMatch(bible, /html\.dark \.profile-card::after/);
assert.match(bible, /position: absolute;/);
assert.match(bible, /width: min\(var\(--display-panel-width\), calc\(100vw - \(var\(--display-viewport-inset\) \* 2\)\)\);/);
assert.doesNotMatch(bible, /max-height: calc\(100dvh - 96px - env\(safe-area-inset-bottom, 0px\)\);/);
assert.match(bible, /\.bottom-chrome \{[\s\S]*position: fixed;[\s\S]*inset: 0;[\s\S]*display: flex;[\s\S]*justify-content: space-between;[\s\S]*pointer-events: none;/);
assert.match(bible, /:root \{[\s\S]*--floating-nav-book-width: 16ch;/);
assert.match(bible, /\.floating-nav \{[\s\S]*position: static;[\s\S]*flex: 0 1 auto;[\s\S]*background: var\(--float-nav-bg\);[\s\S]*box-shadow: var\(--float-nav-shadow\);/);
assert.doesNotMatch(bible, /\.floating-nav \{[^}]*flex: 1 1 auto;/);
assert.match(bible, /\.floating-nav \.fn-book \{[\s\S]*flex: 0 1 auto;[\s\S]*flex-basis: var\(--floating-nav-book-width\);[\s\S]*width: var\(--floating-nav-book-width\);[\s\S]*max-width: var\(--floating-nav-book-width\);/);
assert.match(bible, /\.action-chrome \{[\s\S]*position: static;[\s\S]*flex: 0 0 auto;[\s\S]*background: var\(--float-nav-bg\);[\s\S]*box-shadow: var\(--float-nav-shadow\);/);
assert.match(bible, /\.bottom-actions \{[\s\S]*display: flex;[\s\S]*background: transparent;[\s\S]*border: 0;[\s\S]*box-shadow: none;[\s\S]*backdrop-filter: none;/);
assert.match(bible, /\.bottom-action-button \{[\s\S]*min-height: var\(--display-control-height\);[\s\S]*display: inline-flex;[\s\S]*align-items: center;[\s\S]*justify-content: center;[\s\S]*line-height: 1\.15;/);
assert.match(bible, /\.bottom-history-menu \{[\s\S]*position: fixed;[\s\S]*right: 12px;[\s\S]*bottom: var\(--bottom-chrome-clearance\);[\s\S]*width: min\(420px, calc\(100vw - 24px\)\);[\s\S]*max-height: calc\(100dvh - var\(--bottom-chrome-clearance\) - 12px\);[\s\S]*display: grid;[\s\S]*grid-auto-rows: minmax\(0, auto\);[\s\S]*overflow-y: auto;[\s\S]*overscroll-behavior: contain;[\s\S]*background: var\(--float-nav-bg\);[\s\S]*backdrop-filter: var\(--hdr-blur\);[\s\S]*-webkit-backdrop-filter: var\(--hdr-blur\);[\s\S]*isolation: isolate;[\s\S]*z-index: 132;[\s\S]*opacity: 0;[\s\S]*visibility: hidden;[\s\S]*pointer-events: none;[\s\S]*transform: translateY\(6px\) scale\(\.98\);[\s\S]*transition-property: opacity, transform, visibility;[\s\S]*transition-duration: 180ms, 180ms, 0s;[\s\S]*transition-delay: 0s, 0s, 180ms;/);
assert.match(bible, /\.bottom-history-menu\.open \{[\s\S]*opacity: 1;[\s\S]*visibility: visible;[\s\S]*pointer-events: auto;[\s\S]*transform: translateY\(0\) scale\(1\);[\s\S]*transition-property: opacity, transform, visibility;[\s\S]*transition-duration: 180ms, 180ms, 0s;/);
assert.match(bible, /\.bottom-history-menu \.dd-item \{[\s\S]*min-width: 0;[\s\S]*min-height: 24px;[\s\S]*align-items: center;[\s\S]*padding: min\(7px, calc\(var\(--display-control-pad-y\) \* \.875\)\) min\(10px, calc\(var\(--display-control-pad-x\) \/ 1\.2\)\);[\s\S]*background: color-mix\(in srgb, var\(--surface\) 72%, transparent\);/);
assert.match(bible, /\.bottom-history-menu \.dd-title \{[\s\S]*font-size: var\(--display-control-font-size\);[\s\S]*line-height: 1\.15;/);
assert.match(bible, /\.bottom-history-menu \.dd-meta \{[\s\S]*font-size: var\(--text-15\);[\s\S]*line-height: 1\.15;/);
assert.match(bible, /\.dd-item \.dd-label \{ flex: 1; min-width: 0; \}/);
assert.match(bible, /\.dd-empty \{[\s\S]*padding: var\(--display-panel-padding\);[\s\S]*font-size: var\(--display-control-font-size\);[\s\S]*text-align: center;/);
assert.match(bible, /\.marquee-line \{[^}]*overflow: hidden;[^}]*white-space: nowrap;[^}]*\}/);
assert.match(bible, /\.marquee-line\.is-marquee \.marquee-text \{[\s\S]*animation: marquee-sway 3s var\(--motion-ease\) infinite alternate;/);
assert.match(bible, /@keyframes marquee-sway \{[\s\S]*translateX\(calc\(var\(--marquee-distance, 0px\) \* -1\)\)/);
assert.doesNotMatch(bible, /--marquee-(?:left|right)-fade/);
assert.doesNotMatch(marqueeDeclarations, /(?:^|[;\s])(?:mask|mask-image|-webkit-mask|-webkit-mask-image)\s*:/);
assert.doesNotMatch(bible, /marquee-mask-breathe/);
assert.match(bible, /\.dd-item \.dd-title \{[\s\S]*overflow: hidden;[\s\S]*white-space: nowrap;/);
assert.match(bible, /\.dd-item \.dd-meta \{[\s\S]*overflow: hidden;[\s\S]*white-space: nowrap;[\s\S]*font-size: var\(--text-15\);/);
assert.match(bible, /@media \(max-width: 640px\) \{[\s\S]*\.floating-nav \{[\s\S]*top: calc\(8px \+ env\(safe-area-inset-top, 0px\)\);[\s\S]*bottom: auto;/);
assert.match(bible, /@media \(max-width: 640px\) \{[\s\S]*\.floating-nav \.fn-book \{ flex: 1 1 auto; width: auto; max-width: 42vw; \}/);
assert.match(bible, /@media \(max-width: 640px\) \{[\s\S]*\.floating-nav \.fn-book \.marquee-line \{ width: 100%; \}/);
assert.match(bible, /@media \(max-width: 640px\) \{[\s\S]*\.action-chrome \{[\s\S]*left: 12px;[\s\S]*right: 12px;/);
assert.match(bible, /@media \(max-width: 640px\) \{[\s\S]*\.bottom-actions \{ flex: 1 1 auto; justify-content: flex-start; \}/);
assert.match(bible, /@media \(max-width: 640px\) \{[\s\S]*\.bottom-actions \.bottom-action-button \{ flex: 1 1 0; \}/);
assert.match(bible, /@media \(max-width: 640px\) \{[\s\S]*\.fab-root \{ margin-left: auto; align-self: center; \}/);
assert.match(bible, /@media \(max-width: 640px\) \{[\s\S]*\.fab-main \{ width: var\(--display-icon-button-size\); height: var\(--display-control-height\); min-height: var\(--display-control-height\); \}/);
assert.doesNotMatch(bible, /@media \(max-width: 640px\) \{[\s\S]*\.fab-panel \{ bottom: calc\(118px \+ env\(safe-area-inset-bottom, 0px\)\); \}/);
assert.match(bible, /<div id="auth-area" class="fab-card profile-card"><\/div>/);
assert.match(bible, /<div class="fab-card setting-control-wrap">[\s\S]*<label class="fab-card-title" for="theme-mode-select">Appearance<\/label>[\s\S]*<select id="theme-mode-select" class="setting-select">/);
assert.match(bible, /<label class="fab-card-title" for="text-scale-select">Text Scale<\/label>[\s\S]*<select id="text-scale-select" class="setting-select">[\s\S]*<option value="50">50%<\/option>[\s\S]*<option value="150">150%<\/option>/);
assert.doesNotMatch(bible, /<label for="font-size-slider">Text Size<\/label>/);
assert.doesNotMatch(bible, /<output id="dd-font-val"/);
assert.doesNotMatch(bible, /class="fab-card history-card"/);
assert.doesNotMatch(bible, /class="fab-card search-card"/);
assert.match(bible, /<div class="action-chrome" id="action-chrome">\s*<div class="bottom-actions" aria-label="Quick actions">[\s\S]*<button class="bottom-action-button" id="btn-history" type="button">[\s\S]*History[\s\S]*<button class="bottom-action-button" id="btn-search" type="button">[\s\S]*Search[\s\S]*<\/div>\s*<div class="fab-root">/);
assert.match(bible, /<\/div>\s*<div id="history-menu" class="bottom-history-menu" aria-label="Reading history" hidden inert><\/div>\s*<div id="fab-panel" class="fab-panel" hidden inert>/);
assert.match(bible, /\.view-inner \{[\s\S]*padding: 16px var\(--ui-view-pad\);[\s\S]*padding-top: calc\(16px \+ var\(--top-chrome-clearance\)\);[\s\S]*padding-bottom: calc\(16px \+ var\(--bottom-chrome-clearance\)\);/);
assert.match(bible, /\.floating-nav \{[\s\S]*justify-content: flex-start;[\s\S]*width: auto;[\s\S]*max-width: min\(720px, calc\(100% - 180px\)\);[\s\S]*min-width: 0;[\s\S]*flex: 0 1 auto;/);
assert.match(bible, /\.floating-nav button \{[\s\S]*font-size: var\(--display-control-font-size\);[\s\S]*min-height: var\(--display-control-height\);[\s\S]*display: inline-flex;[\s\S]*align-items: center;[\s\S]*justify-content: center;[\s\S]*line-height: 1\.15;/);
assert.match(bible, /\.bottom-action-button \{[\s\S]*font-size: var\(--display-control-font-size\);[\s\S]*padding: var\(--display-control-pad-y\) var\(--display-control-pad-x\);/);
assert.match(bible, /\.dd-item \{[\s\S]*font-size: var\(--display-control-font-size\);/);
assert.match(bible, /\.setting-select \{[\s\S]*width: 100%;[\s\S]*height: var\(--display-segment-height\);[\s\S]*font-size: var\(--display-control-font-size\);/);
assert.match(bible, /\.setting-control-wrap \{[\s\S]*gap: var\(--display-panel-gap\);[\s\S]*min-width: 0;/);
assert.match(bible, /\.app-version \{[\s\S]*display: flex;[\s\S]*align-items: center;[\s\S]*justify-content: center;[\s\S]*gap: var\(--display-panel-gap\);[\s\S]*padding: var\(--display-panel-gap\) min\(16px, calc\(var\(--display-panel-padding\) \* 1\.3333\)\) max\(min\(2px, calc\(var\(--display-panel-gap\) \* \.25\)\), env\(safe-area-inset-bottom, 0px\)\);[\s\S]*font-size: var\(--text-14\);/);
assert.match(bible, /\.app-version-label \{[\s\S]*flex: 0 0 auto;/);
assert.match(bible, /\.app-version-status \{[\s\S]*min-width: 0;[\s\S]*color: var\(--fg3\);[\s\S]*overflow: hidden;[\s\S]*white-space: nowrap;/);
assert.match(bible, /\.app-version-separator \{[\s\S]*color: var\(--fg4\);/);
assert.match(bible, /\.app-version-separator\[hidden\] \{ display: none; \}/);
assert.match(bible, /\.app-version \.dd-signout-button \{[\s\S]*flex: 0 0 auto;[\s\S]*font-size: var\(--text-15\);[\s\S]*min-height: max\(24px, min\(34px, var\(--display-control-height\)\)\);[\s\S]*padding: min\(6px, var\(--display-control-pad-y\)\) min\(10px, var\(--display-control-pad-x\)\);/);
assert.match(bible, /\.app-version \.dd-signout-button\[hidden\] \{[\s\S]*display: none;/);
assert.match(bible, /\.book-name-en \{ font-size: var\(--display-control-font-size\);[\s\S]*overflow: hidden; white-space: nowrap;/);
assert.match(bible, /\.book-name-ko \{ font-size: var\(--text-17\);[\s\S]*overflow: hidden; white-space: nowrap;/);
assert.match(bible, /\.testament \{[\s\S]*min-width: 0;[\s\S]*background: var\(--card-bg\);[\s\S]*border: var\(--card-border\);[\s\S]*border-radius: var\(--radius-md\);[\s\S]*box-shadow: var\(--shadow\);[\s\S]*padding: var\(--display-panel-padding\);/);
assert.match(bible, /\.testament h2 \{[\s\S]*font-size: var\(--display-control-font-size\);[\s\S]*overflow: hidden; white-space: nowrap;/);
assert.doesNotMatch(bible, /\.testament h2 \{[\s\S]*border-bottom: 1px solid var\(--border2\);/);
assert.match(bible, /otDiv\.className = 'testament';[\s\S]*var otH = document\.createElement\('h2'\); setMarqueeText\(otH, 'Old Testament'\);/);
assert.match(bible, /ntDiv\.className = 'testament';[\s\S]*var ntH = document\.createElement\('h2'\); setMarqueeText\(ntH, 'New Testament'\);/);
assert.match(bible, /\.selection-card \{[\s\S]*background: var\(--card-bg\);[\s\S]*border: var\(--card-border\);[\s\S]*border-radius: var\(--radius-md\);[\s\S]*box-shadow: var\(--shadow\);[\s\S]*padding: var\(--display-panel-padding\);/);
assert.match(bible, /\.chapters-header \{ font-size: var\(--text-22\);[\s\S]*overflow: hidden; white-space: nowrap;/);
assert.match(bible, /var card = document\.createElement\('section'\);[\s\S]*card\.className = 'selection-card';[\s\S]*setMarqueeText\(header, bookName \+ ' - Chapters'\);[\s\S]*card\.appendChild\(header\);[\s\S]*card\.appendChild\(grid\);[\s\S]*viewInner\.appendChild\(card\);/);
assert.match(bible, /var card = document\.createElement\('section'\);[\s\S]*card\.className = 'selection-card';[\s\S]*setMarqueeText\(header, bookName \+ ' - Chapter ' \+ chapterNum \+ ' - Verses'\);[\s\S]*card\.appendChild\(header\);[\s\S]*card\.appendChild\(grid\);[\s\S]*viewInner\.appendChild\(card\);/);
assert.match(bible, /\.chapter-btn \{[\s\S]*min-height: var\(--display-control-height\);[\s\S]*font-size: var\(--display-control-font-size\);/);
assert.match(bible, /\.search-input \{[\s\S]*font-size: var\(--display-control-font-size\);/);
assert.match(bible, /\.search-hist-item \.sh-query \{[\s\S]*flex: 1;[\s\S]*font-size: var\(--display-control-font-size\);/);
assert.match(bible, /\.search-text \{[\s\S]*font-size: var\(--text-18\);/);
assert.match(bible, /\.floating-nav \{[^}]*box-shadow: var\(--float-nav-shadow\);/);
assert.match(bible, /\.floating-nav \.fn-chapter,\n  \.floating-nav \.fn-verse \{[\s\S]*min-width: 44px;/);
assert.doesNotMatch(bible, /\.floating-nav \.fn-chapter \{[\s\S]*min-width: 36px;/);
assert.match(bible, /\.fab-root \{[\s\S]*margin-left: auto;/);
assert.match(bible, /\.fab-main \{[\s\S]*position: relative;[\s\S]*padding: 0;[\s\S]*overflow: hidden;/);
assert.match(bible, /\.fab-main \.profile-avatar \{[\s\S]*position: absolute;[\s\S]*inset: 0;[\s\S]*width: 100%;[\s\S]*height: 100%;[\s\S]*min-width: 100%;[\s\S]*min-height: 100%;[\s\S]*max-width: none;[\s\S]*border-radius: 0;[\s\S]*object-fit: cover;[\s\S]*border: 0;/);
assert.match(bible, /\.dd-signout-button \{[\s\S]*flex-shrink: 0;[\s\S]*border-radius: var\(--radius-xs\);[\s\S]*font-size: var\(--text-13\);[\s\S]*min-height: max\(24px, min\(34px, var\(--display-control-height\)\)\); padding: min\(6px, var\(--display-control-pad-y\)\) min\(10px, var\(--display-control-pad-x\)\);/);
assert.match(bible, /\.dd-user-name \{[\s\S]*font-size: var\(--display-control-font-size\);[\s\S]*line-height: 1\.2;[\s\S]*overflow: hidden; white-space: nowrap;/);
assert.match(bible, /\.dd-user-email \{[\s\S]*font-size: var\(--text-15\);[\s\S]*line-height: 1\.2;[\s\S]*overflow: hidden; white-space: nowrap;/);
assert.match(bible, /\.dd-sync-status \{[\s\S]*font-size: var\(--text-14\);[\s\S]*line-height: 1\.2;[\s\S]*overflow: hidden; white-space: nowrap;/);
assert.match(bible, /\.profile-card \.dd-user-photo \{[\s\S]*position: relative;[\s\S]*left: auto;[\s\S]*top: auto;[\s\S]*bottom: auto;[\s\S]*width: auto;[\s\S]*height: 100%;[\s\S]*min-height: 0;[\s\S]*max-width: 45%;[\s\S]*flex: 0 1 auto;[\s\S]*align-self: stretch;[\s\S]*object-fit: cover;[\s\S]*object-position: center;[\s\S]*border-radius: 0;/);
assert.doesNotMatch(bible, /clip-path: inset\(0 max\(0px, calc\(100% - var\(--profile-photo-width\)\)\) 0 0\);/);
assert.doesNotMatch(bible, /--profile-photo-width:/);
assert.match(bible, /\.profile-card \.dd-user \{[\s\S]*height: max\(24px, min\(92px, var\(--profile-photo-height\)\)\);[\s\S]*min-height: 0;[\s\S]*align-items: stretch;[\s\S]*gap: var\(--display-panel-padding\);[\s\S]*margin-left: 0;[\s\S]*\}/);
assert.match(bible, /\.profile-card \.dd-user-info \{[\s\S]*position: relative;[\s\S]*z-index: 1;[\s\S]*display: flex;[\s\S]*flex-direction: column;[\s\S]*justify-content: center;[\s\S]*gap: 2px;[\s\S]*padding: var\(--display-panel-padding\) var\(--display-panel-padding\) var\(--display-panel-padding\) 0;/);
assert.doesNotMatch(bible, /\.profile-card \.dd-signout-button/);
assert.match(bible, /\.profile-card \.dd-signin-button \{[\s\S]*width: 100%;[\s\S]*min-height: calc\(var\(--display-control-height\) \+ \(var\(--display-panel-padding\) \* 2\)\);[\s\S]*justify-content: center;[\s\S]*border: 0;[\s\S]*border-bottom: 0;[\s\S]*border-radius: var\(--radius-sm\);[\s\S]*background: transparent;[\s\S]*box-shadow: inset 0 0 0 1px transparent, 0 1px 8px transparent;[\s\S]*transition-property: background, color, box-shadow, transform;[\s\S]*transition-duration: 180ms, 180ms, 180ms, 120ms;/);
assert.match(bible, /\.profile-card \.dd-signin-button \.dd-label \{[\s\S]*flex: 0 1 auto;/);
assert.match(bible, /\.profile-card\.signed-out \.dd-signin-button:hover,\n  \.profile-card\.signed-out \.dd-signin-button:focus-visible \{[\s\S]*background: var\(--hover-bg\);[\s\S]*box-shadow: inset 0 0 0 1px var\(--accent\), 0 1px 8px var\(--accent-glow\);[\s\S]*transform: none;/);
assert.doesNotMatch(bible, /\.profile-card\.signed-out \.dd-signin-button:hover,[\s\S]*transform: translateY\(-1px\);/);
assert.match(bible, /\.profile-card\.signed-out \.dd-signin-button:active \{[\s\S]*transform: scale\(\.985\);/);
assert.match(bible, /details\.appendChild\(account\);/);
assert.doesNotMatch(bible, /details\.appendChild\(status\);/);
assert.doesNotMatch(bible, /authArea\.appendChild\(status\);/);
assert.match(bible, /<div id="floating-nav" class="floating-nav hidden" role="navigation" aria-label="Chapter">[\s\S]*<\/div>\s*<div class="action-chrome" id="action-chrome">[\s\S]*<div class="bottom-actions" aria-label="Quick actions">[\s\S]*<\/div>\s*<div class="fab-root">[\s\S]*id="fab-main"[\s\S]*<\/div>\s*<\/div>\s*<\/div>\s*<div id="history-menu" class="bottom-history-menu" aria-label="Reading history" hidden inert><\/div>\s*<div id="fab-panel" class="fab-panel" hidden inert>/);
assert.doesNotMatch(bible, /width: 100vw;/);
assert.match(bible, /var fabPanelHistoryOpen = false;/);
assert.match(bible, /var suppressNextPopupPop = false;/);
assert.match(bible, /function currentNavStateForHistory\(\)/);
assert.match(bible, /function openFabPanel\(pushHistory\)/);
assert.match(bible, /history\.pushState\(Object\.assign\(currentNavStateForHistory\(\), \{ popup: 'menu' \}\), ''\);/);
assert.match(bible, /function ensurePopupHistory\(pushHistory\) \{[\s\S]*if \(pushHistory && !fabPanelHistoryOpen\) \{[\s\S]*history\.pushState\(Object\.assign\(currentNavStateForHistory\(\), \{ popup: 'menu' \}\), ''\);[\s\S]*fabPanelHistoryOpen = true;[\s\S]*\}/);
assert.match(bible, /function closeMenus\(options\)/);
assert.match(bible, /var exceptFab = options\.exceptFab === true;/);
assert.match(bible, /var exceptMenu = options\.exceptMenu \|\| null;/);
assert.match(bible, /if \(fabPanel\.classList\.contains\('open'\) && !exceptFab\)/);
assert.match(bible, /if \(openMenu && openMenu !== exceptMenu\) \{ openMenu\.classList\.remove\('open'\); openMenu = null; closedPopup = true; \}/);
assert.match(bible, /if \(closedPopup && fabPanelHistoryOpen && !options\.fromPop && !options\.keepHistory\)/);
assert.match(bible, /suppressNextPopupPop = true;[\s\S]*history\.back\(\);/);
assert.match(bible, /closeMenus\(\{ exceptFab: true, keepHistory: true \}\);[\s\S]*ensurePopupHistory\(pushHistory\);/);
assert.match(bible, /closeMenus\(\{ exceptMenu: menu, keepHistory: true \}\);[\s\S]*ensurePopupHistory\(true\);[\s\S]*menu\.classList\.add\('open'\);/);
assert.match(bible, /fabMain\.addEventListener\('click',[\s\S]*openAppSheet\('settings', \{ opener: fabMain \}\);/);
assert.doesNotMatch(bible, /\.fab-panel \{[^}]*height: 100dvh;/);
assert.doesNotMatch(bible, /\.fab-root:has\(\.fab-panel\.open\) \.fab-main/);
assert.doesNotMatch(bible, /id="fab-close"/);
assert.doesNotMatch(bible, /fabClose\.addEventListener\('click'/);
assert.match(bible, /authArea\.classList\.toggle\('signed-in', !!user\);/);
assert.match(bible, /authArea\.classList\.toggle\('signed-out', !user\);/);
assert.match(bible, /var footerSignout = document\.getElementById\('footer-signout'\);/);
assert.match(bible, /var footerStatus = document\.getElementById\('footer-status'\);/);
assert.match(bible, /var footerSignoutSeparator = document\.getElementById\('footer-signout-separator'\);/);
assert.match(bible, /_syncStatusEl = footerStatus;/);
assert.match(bible, /footerSignout\.addEventListener\('click', function \(\) \{[\s\S]*auth\.signOut\(\);[\s\S]*closeMenus\(\{ keepHistory: true \}\);[\s\S]*\}\);/);
assert.match(bible, /footerSignout\.hidden = !user;/);
assert.match(bible, /footerSignoutSeparator\.hidden = !user;/);
assert.match(bible, /setMarqueeText\(footerStatus, user \? 'Checking sync\\u2026' : 'Signed out'\);/);
assert.match(bible, /function _setSyncStatus\(text\) \{[\s\S]*if \(_syncStatusEl\) setMarqueeText\(_syncStatusEl, text\);[\s\S]*\}/);
assert.match(bible, /setMarqueeText\(name, user\.displayName \|\| 'Signed In'\);/);
assert.match(bible, /setMarqueeText\(email, user\.email \|\| ''\);/);
assert.match(bible, /setMarqueeText\(account, 'Google Account'\);/);
assert.doesNotMatch(bible, /setMarqueeText\(status, navigator\.onLine \? 'Synced \\u2713' : 'Offline \\u2014 will sync later'\);/);
assert.doesNotMatch(bible, /outBtn\.className = 'dd-signout-button';/);
assert.doesNotMatch(bible, /outBtn\.textContent = 'Sign Out';/);
assert.doesNotMatch(bible, /info\.appendChild\(outBtn\);/);
assert.doesNotMatch(bible, /outBtn\.className = 'dd-item';/);
assert.doesNotMatch(bible, /authArea\.appendChild\(outBtn\);/);
assert.match(bible, /inBtn\.className = 'dd-item dd-signin-button';/);

assert.match(bible, /id="fn-verse"/);
const appSheetDialogs = bible.match(/<dialog\b[^>]*\bid="app-sheet"[^>]*>/g) || [];
assert.equal(appSheetDialogs.length, 1, 'one persistent app sheet dialog is present');
assert.match(appSheetDialogs[0], /aria-label="Bible panel"/);
assert.match(bible, /id="app-sheet-handle"[^>]*aria-label="Expand Bible panel"/);
assert.match(bible, /id="app-sheet-measure" class="app-sheet-measure"/);
assert.match(bible, /class="app-sheet-fade app-sheet-fade-top" aria-hidden="true"/);
assert.match(bible, /class="app-sheet-fade app-sheet-fade-bottom" aria-hidden="true"/);
assert.doesNotMatch(bible, /aria-labelledby="app-sheet-title"|id="app-sheet-title"|id="app-sheet-close"|class="app-sheet-header"/);
assert.doesNotMatch(bible, /\bappSheetTitle\b|\bappSheetClose\b/);
assert.match(bible, /\.app-sheet\.edge-top \.app-sheet-handle\s*\{[^}]*order:\s*3/);
assert.match(bible, /function showVersePickerView\(bookName, chapterNum\)/);
assert.match(bible, /view: 'verse-picker'/);
assert.match(bible, /fnVerse\.textContent = activeVerse \? activeVerse : '1';/);
assert.doesNotMatch(bible, /fnVerse\.textContent = activeVerse \? activeVerse : 'Verse';/);
assert.doesNotMatch(bible, /fnVerse\.textContent = activeVerse \? ':' \+ activeVerse : 'Verse';/);
assert.match(bible, /setActiveVerse\(selectedVerse, false\)/);
assert.match(bible, /var verseChaseFrame = null;/);
assert.match(bible, /var verseChaseTarget = null;/);
assert.match(bible, /var verseChaseStartTop = 0;/);
assert.match(bible, /var verseChaseDestinationTop = 0;/);
assert.match(bible, /var verseChaseStartTime = null;/);
assert.match(bible, /var verseChaseDuration = 0;/);
assert.match(bible, /var CHAPTER_CROSSFADE_MS = 200;/);
assert.match(bible, /var lastViewScrollTop = 0;/);
assert.match(bible, /var bottomChromeScrollFrame = null;/);
assert.match(bible, /var bottomChrome = document\.getElementById\('bottom-chrome'\);/);
assert.match(bible, /var actionChrome = document\.getElementById\('action-chrome'\);/);
assert.match(bible, /var bottomChromeResizeObserver = null;/);
assert.match(bible, /var marqueeFrame = null;/);
assert.match(bible, /function measureMarqueeLines\(root\) \{[\s\S]*text\.scrollWidth - line\.clientWidth[\s\S]*line\.classList\.toggle\('is-marquee', distance > 1\);[\s\S]*\}/);
assert.match(bible, /line\.style\.setProperty\('--marquee-distance', Math\.ceil\(distance\) \+ 'px'\);/);
assert.match(bible, /function setMarqueeText\(el, value\) \{[\s\S]*el\.classList\.add\('marquee-line'\);[\s\S]*text\.className = 'marquee-text';[\s\S]*scheduleMarqueeMeasure\(\);[\s\S]*\}/);
assert.match(bible, /function updateBottomChromeClearance\(\) \{[\s\S]*window\.matchMedia\('\(max-width: 640px\)'\)\.matches[\s\S]*floatingNav\.offsetHeight[\s\S]*actionChrome\.offsetHeight[\s\S]*setProperty\('--top-chrome-clearance',[\s\S]*setProperty\('--bottom-chrome-clearance',/);
assert.match(bible, /function scheduleBottomChromeClearanceUpdate\(\) \{[\s\S]*updateBottomChromeClearance\(\);[\s\S]*requestAnimationFrame\(updateBottomChromeClearance\);[\s\S]*\}/);
assert.match(bible, /function observeBottomChromeClearance\(\) \{[\s\S]*window\.addEventListener\('resize', function \(\) \{[\s\S]*scheduleMarqueeMeasure\(\);[\s\S]*window\.addEventListener\('orientationchange', function \(\) \{[\s\S]*scheduleMarqueeMeasure\(\);[\s\S]*bottomChromeResizeObserver = new ResizeObserver\(updateBottomChromeClearance\);[\s\S]*bottomChromeResizeObserver\.observe\(floatingNav\);[\s\S]*bottomChromeResizeObserver\.observe\(actionChrome\);[\s\S]*\}/);
assert.match(bible, /function setBottomChromeHidden\(hidden\) \{[\s\S]*if \(fabPanel\.classList\.contains\('open'\) \|\| openMenu\) hidden = false;[\s\S]*bottomChrome\.classList\.toggle\('scroll-hidden', hidden\);[\s\S]*scheduleBottomChromeClearanceUpdate\(\);[\s\S]*\}/);
assert.match(bible, /function updateBottomChromeFromScroll\(\) \{[\s\S]*var delta = nextTop - lastViewScrollTop;[\s\S]*if \(nextTop <= 4\) setBottomChromeHidden\(false\);[\s\S]*else if \(Math\.abs\(delta\) >= 8\) setBottomChromeHidden\(delta > 0\);[\s\S]*lastViewScrollTop = nextTop;[\s\S]*\}/);
assert.match(bible, /function resetBottomChromeScrollState\(\) \{[\s\S]*lastViewScrollTop = viewEl\.scrollTop;[\s\S]*setBottomChromeHidden\(false\);[\s\S]*\}/);
assert.match(bible, /function scheduleBottomChromeScrollUpdate\(\) \{[\s\S]*bottomChromeScrollFrame = requestAnimationFrame\(updateBottomChromeFromScroll\);[\s\S]*\}/);
assert.match(bible, /openFabPanel\(pushHistory\) \{[\s\S]*setBottomChromeHidden\(false\);[\s\S]*fabPanel\.classList\.add\('open'\);[\s\S]*scheduleBottomChromeClearanceUpdate\(\);/);
assert.match(bible, /observeBottomChromeClearance\(\);/);
assert.match(bible, /function readingViewportMetrics\(\)/);
assert.match(bible, /var bottomRect = actionChrome \? actionChrome\.getBoundingClientRect\(\) : null;/);
assert.match(bible, /var bottomLimit = bottomRect \? Math\.min\(viewRect\.bottom, bottomRect\.top\) : viewRect\.bottom;/);
assert.match(bible, /centerY: topLimit \+ \(height \/ 2\)/);
assert.match(bible, /function desiredVerseScrollTop\(target\)/);
assert.match(bible, /var metrics = readingViewportMetrics\(\);[\s\S]*var desiredTop = viewEl\.scrollTop \+ \(targetRect\.top - metrics\.top\) - \(\(metrics\.height - targetRect\.height\) \/ 2\);/);
assert.match(bible, /function shouldReduceVerseMotion\(\)/);
assert.match(bible, /function stopVerseChase\(\)/);
assert.match(bible, /function releaseVerseChaseForFreeScroll\(\)/);
assert.match(bible, /function setVerseChaseTarget\(target\)/);
assert.match(bible, /function stepVerseChase\(ts\)/);
assert.match(bible, /function scrollVerseToCenter\(target\)/);
assert.match(bible, /if \(verseChaseTarget\) return;/);
assert.match(bible, /var metrics = readingViewportMetrics\(\);[\s\S]*var centerY = metrics\.centerY;/);
assert.match(bible, /var visible = rect\.bottom > metrics\.top && rect\.top < metrics\.bottom;/);
assert.match(bible, /Math\.min\(maxTop, Math\.max\(0, desiredTop\)\)/);
assert.match(bible, /setVerseChaseTarget\(target\);/);
assert.doesNotMatch(bible, /function verseEaseLateBrake/);
assert.doesNotMatch(bible, /var duration = Math\.min\(780/);
assert.match(bible, /\.verse-edge-spacer/);
assert.match(bible, /\.verse-head-spacer/);
assert.match(bible, /\.verse-tail-spacer/);
assert.match(bible, /headSpacer\.className = 'verse-edge-spacer verse-head-spacer';/);
assert.match(bible, /tailSpacer\.className = 'verse-edge-spacer verse-tail-spacer';/);
assert.doesNotMatch(bible, /ACTIVE_VERSE_SETTLE_MS/);
assert.doesNotMatch(bible, /activeVerseTimer/);
assert.doesNotMatch(bible, /function scheduleActiveVerseCenter/);
assert.doesNotMatch(bible, /scheduleActiveVerseCenter\(/);
assert.doesNotMatch(bible, /function isNearScrollBottom\(\)/);
assert.doesNotMatch(bible, /scrollIntoView\(\{ behavior: 'smooth', block: 'center' \}\)/);
assert.match(bible, /\.verse\.active/);

assert.match(bible, /--verse-num: #0b63ce;/);
assert.match(bible, /--verse-num: #8bb9ff;/);

assert.match(bible, /document\.addEventListener\('keydown', handleBibleKeyboardNavigation\);/);
assert.match(bible, /viewEl\.addEventListener\('wheel', releaseVerseChaseForFreeScroll, \{ passive: true \}\);/);
assert.match(bible, /viewEl\.addEventListener\('touchstart', releaseVerseChaseForFreeScroll, \{ passive: true \}\);/);
assert.match(bible, /function handleBibleKeyboardNavigation\(e\)/);
assert.match(bible, /function shouldIgnoreBibleShortcut\(e\)/);
assert.match(bible, /tag === 'INPUT' \|\| tag === 'TEXTAREA' \|\| tag === 'SELECT'/);
assert.match(bible, /e\.metaKey \|\| e\.ctrlKey \|\| e\.altKey/);
assert.match(bible, /function handleSelectionArrowKey\(key\)/);
assert.match(bible, /function focusClosestGridItem\(items, current, key\)/);
assert.match(bible, /getBoundingClientRect\(\)/);
assert.match(bible, /candidate\.score = directionalDistance\(currentRect, rect, key\);/);
assert.match(bible, /function handleSelectionEnterKey\(\)/);
assert.match(bible, /document\.activeElement\.click\(\);/);
assert.match(bible, /function handleReadingEnterKey\(target\)/);
assert.match(bible, /var active = viewInner\.querySelector\('\.verse\.active'\);/);
assert.match(bible, /var noteButtons = verseEl\.querySelectorAll\('\.footnote-toggle'\);/);
assert.match(bible, /var noteBodies = verseEl\.querySelectorAll\('\.footnote-body'\);/);
assert.match(bible, /noteBodies\[i\]\.classList\.toggle\('visible', shouldOpen\);/);
assert.match(bible, /noteButtons\[i\]\.classList\.toggle\('open', shouldOpen\);/);
assert.match(bible, /verseEl\.classList\.toggle\('footnotes-open', shouldOpen\);/);
assert.match(bible, /function syncFootnoteVerseState\(verseEl\)/);
assert.match(bible, /verseEl\.classList\.toggle\('footnotes-open', hasVisibleNote\);/);
assert.match(bible, /syncFootnoteVerseState\(bd\.parentElement\);/);
assert.match(bible, /function handleKeyboardBack\(\)/);
assert.match(bible, /if \(uiView === 'verse-picker'\) \{ showChaptersViewWithTransition\(navBook\); return true; \}/);
assert.match(bible, /if \(uiView === 'chapters'\) \{ showBooksViewWithTransition\(\); return true; \}/);
assert.match(bible, /if \(uiView === 'verses'\) \{ showVersePickerViewWithTransition\(navBook, navChapter\); return true; \}/);
assert.match(bible, /function handleReadingArrowKey\(key\)/);
assert.match(bible, /if \(key === 'ArrowLeft'\) return showAdjacentChapter\(-1\);/);
assert.match(bible, /if \(key === 'ArrowRight'\) return showAdjacentChapter\(1\);/);
assert.match(bible, /if \(key === 'ArrowUp'\) return showAdjacentVerse\(-1\);/);
assert.match(bible, /if \(key === 'ArrowDown'\) return showAdjacentVerse\(1\);/);
assert.match(bible, /function showAdjacentChapter\(direction\)/);
assert.match(bible, /direction < 0 \? prevChapterNav\(navBook, navChapter\) : nextChapterNav\(navBook, navChapter\)/);
assert.match(bible, /function showAdjacentVerse\(direction\)/);
assert.match(bible, /scrollVerseToCenter\(target\);/);
assert.match(bible, /if \(key === 'Enter'\) handled = uiView === 'verses' \? handleReadingEnterKey\(e\.target\) : handleSelectionEnterKey\(\);/);
assert.match(bible, /if \(key === 'Escape' \|\| key === 'Backspace' \|\| key === 'Delete'\) handled = handleKeyboardBack\(\);/);
assert.match(bible, /if \(suppressNextPopupPop\) \{[\s\S]*suppressNextPopupPop = false;[\s\S]*return;[\s\S]*\}/);
assert.match(bible, /if \(fabPanel\.classList\.contains\('open'\) \|\| openMenu\) \{[\s\S]*closeMenus\(\{ fromPop: true \}\);[\s\S]*return;[\s\S]*\}/);
assert.match(bible, /if \(s && s\.popup === 'menu'\) \{[\s\S]*openFabPanel\(false\);[\s\S]*return;[\s\S]*\}/);

assert.match(bible, /var chapterCrossfadeTimer = null;/);
assert.match(bible, /\.view-inner\.chapter-transition-retiring/);
assert.match(bible, /\.view-inner\.chapter-transition-ready \{ opacity: 0; transition: none; \}/);
assert.match(bible, /\.view-inner\.chapter-transition-ready\.chapter-transition-in \{[\s\S]*opacity: 1;[\s\S]*transition-property: opacity;[\s\S]*transition-duration: 200ms;[\s\S]*transition-timing-function: var\(--motion-ease\);/);
assert.match(bible, /transition-property: opacity;[\s\S]*transition-duration: 200ms;[\s\S]*transition-timing-function: var\(--motion-ease\);/);
assert.match(bible, /@media \(prefers-reduced-motion: reduce\) \{[\s\S]*?\.view-inner \{[\s\S]*?transition: none;/);
assert.match(bible, /function clearChapterCrossfadeTimer\(\)/);
assert.match(bible, /window\.clearTimeout\(chapterCrossfadeTimer\);/);
assert.match(bible, /function clearRetiringChapterViews\(\)/);
assert.match(bible, /viewEl\.querySelectorAll\('\.chapter-transition-retiring'\)/);
assert.match(bible, /function showVersesViewWithTransition\(bookName, chapterNum, scrollToVerse\)/);
assert.match(bible, /function showViewWithTransition\(renderView\)/);
assert.match(bible, /function showBooksViewWithTransition\(\)/);
assert.match(bible, /function showChaptersViewWithTransition\(bookName\)/);
assert.match(bible, /function showVersePickerViewWithTransition\(bookName, chapterNum\)/);
assert.match(bible, /function showSelectedVerseWithTransition\(bookName, chapterNum, verse\)/);
assert.match(bible, /var retiring = viewInner\.cloneNode\(true\);/);
assert.match(bible, /retiring\.className = 'view-inner chapter-transition-retiring';/);
assert.match(bible, /retiring\.style\.transform = 'translateY\(-' \+ viewEl\.scrollTop \+ 'px\)';/);
assert.match(bible, /viewInner\.classList\.add\('chapter-transition-ready'\);/);
assert.match(bible, /showVersesView\(bookName, chapterNum, scrollToVerse\);/);
assert.match(bible, /void viewInner\.offsetWidth;/);
assert.match(bible, /viewInner\.classList\.add\('chapter-transition-in'\);/);
assert.match(bible, /viewInner\.classList\.remove\('chapter-transition-ready', 'chapter-transition-in'\);/);
assert.match(bible, /viewEl\.addEventListener\('scroll', function \(\) \{[\s\S]*scheduleBottomChromeScrollUpdate\(\);[\s\S]*requestAnimationFrame\(updateActiveVerseFromViewport\);[\s\S]*\}, \{ passive: true \}\);/);
assert.match(bible, /setUIView\('books'\);[\s\S]*resetBottomChromeScrollState\(\);[\s\S]*updateNav\(\);/);
assert.match(bible, /chapterCrossfadeTimer = window\.setTimeout\(function \(\) \{/);
assert.match(bible, /showViewWithTransition\(function \(\) \{ showBooksView\(\); \}\);/);
assert.match(bible, /showViewWithTransition\(function \(\) \{ showChaptersView\(bookName\); \}\);/);
assert.match(bible, /showViewWithTransition\(function \(\) \{ showVersePickerView\(bookName, chapterNum\); \}\);/);
assert.match(bible, /showViewWithTransition\(function \(\) \{ showVersesView\(bookName, chapterNum, verse\); \}\);/);
assert.match(bible, /showVersesViewWithTransition\(next\.book, next\.chapter, recalledChapterVerse\(next\.book, next\.chapter\) \|\| '1'\);/);
assert.match(bible, /fnPrev\.addEventListener\('click',[\s\S]*showAdjacentChapter\(-1\);/);
assert.match(bible, /fnNext\.addEventListener\('click',[\s\S]*showAdjacentChapter\(1\);/);
assert.match(bible, /showBooksViewWithTransition\(\);/);
assert.match(bible, /showChaptersViewWithTransition\(navBook\);/);
assert.match(bible, /showVersePickerViewWithTransition\(navBook, navChapter\);/);
assert.match(bible, /showSelectedVerseWithTransition\(book, ch, verse\);/);
assert.match(bible, /showSelectedVerseWithTransition\(poppedVerse\.book, poppedVerse\.chapter, poppedVerse\.verse\);/);
assert.match(bible, /document\.getElementById\('btn-history'\)\.addEventListener\('click'/);
assert.match(bible, /document\.getElementById\('btn-history'\)\.addEventListener\('click',[\s\S]*openAppSheet\('history', \{ opener: e\.currentTarget \}\);/);
assert.match(bible, /document\.getElementById\('btn-search'\)\.addEventListener\('click',[\s\S]*openAppSheet\('search', \{ opener: e\.currentTarget \}\);/);
assert.match(bible, /normalizeHistoryEntry: function \(entry\) \{[\s\S]*typeof entry === 'string'[\s\S]*return \{ book: parts\[0\], ch: String\(parts\[1\]\), verse: String\(parts\[2\] \|\| '1'\), selectedAt: '' \};/);
assert.match(bible, /pushHistory: function \(book, ch, verse\) \{[\s\S]*selectedAt: new Date\(\)\.toISOString\(\)[\s\S]*var key = normalized\.book \+ '\|' \+ normalized\.ch;/);
assert.match(bible, /function formatHistoryTimestamp\(value\) \{[\s\S]*new Intl\.DateTimeFormat\(undefined,[\s\S]*year: 'numeric'[\s\S]*minute: '2-digit'[\s\S]*\}\)\.format\(date\);/);
assert.match(bible, /setMarqueeText\(title, item\.book \+ ' ' \+ item\.ch \+ ':' \+ item\.verse\);/);
assert.match(bible, /setMarqueeText\(meta, formatHistoryTimestamp\(item\.selectedAt\)\);/);
assert.match(bible, /showVersesView\(book, parseInt\(ch, 10\), verse\);/);
assert.match(bible, /State\.pushHistory\(book, chapter, validChapterVerse\(book, chapter, activeVerse\) \|\| '1'\);/);
assert.match(bible, /function toggleMenu\(menu, e\) \{[\s\S]*setBottomChromeHidden\(false\);[\s\S]*menu\.classList\.add\('open'\);[\s\S]*openMenu = menu;[\s\S]*scheduleBottomChromeClearanceUpdate\(\);[\s\S]*\}/);
assert.match(bible, /function applyTextScale\(value, persist\) \{[\s\S]*State\.setTextScale\(scale\);[\s\S]*scheduleBottomChromeClearanceUpdate\(\);[\s\S]*scheduleMarqueeMeasure\(\);[\s\S]*\}/);

assert.match(bible, /getThemeMode: function \(\) \{/);
assert.match(bible, /var mode = this\._get\('bible_theme_mode', null\);[\s\S]*return 'auto';/);
assert.match(bible, /setThemeMode: function \(mode\) \{/);
assert.match(bible, /mode === 'dark' \|\| mode === 'auto' \? mode : 'light'/);
assert.match(bible, /function preferredDarkQuery\(\)/);
assert.match(bible, /window\.matchMedia\('\(prefers-color-scheme: dark\)'\)/);
assert.match(bible, /function resolveThemeMode\(mode\)/);
assert.match(bible, /if \(mode !== 'auto'\) return mode === 'dark';/);
assert.match(bible, /return preferredDarkQuery\(\) \? preferredDarkQuery\(\)\.matches : false;/);
assert.match(bible, /function applyThemeMode\(mode, persist\)/);
assert.match(bible, /State\.setThemeMode\(mode\);/);
assert.match(bible, /var themeTransitionTimer = null;/);
assert.match(bible, /var themeModeApplied = false;/);
assert.match(bible, /function beginThemeTransition\(\) \{[\s\S]*document\.documentElement\.classList\.add\('theme-transitioning'\);[\s\S]*document\.documentElement\.classList\.remove\('theme-transitioning'\);[\s\S]*\}, THEME_TRANSITION_MS \+ 20\);/);
assert.match(bible, /if \(themeModeApplied && currentDark !== nextDark\) beginThemeTransition\(\);/);
assert.match(bible, /document\.documentElement\.classList\.toggle\('dark', nextDark\);/);
assert.match(bible, /themeModeApplied = true;/);
assert.match(bible, /html\.theme-transitioning,[\s\S]*html\.theme-transitioning \.bottom-chrome,[\s\S]*html\.theme-transitioning \.bottom-history-menu,[\s\S]*transition-property:[\s\S]*background,[\s\S]*color,[\s\S]*transition-duration: 200ms;[\s\S]*transition-timing-function: var\(--motion-ease\);/);
assert.match(bible, /id="theme-mode-select" class="setting-select"/);
assert.match(bible, /\.setting-select \{[\s\S]*transition-property: background, border-color, box-shadow;[\s\S]*transition-duration: 180ms;[\s\S]*transition-timing-function: var\(--motion-ease\);/);
assert.match(bible, /\.setting-select:focus-visible \{[\s\S]*border-color: var\(--accent\);[\s\S]*box-shadow: 0 0 0 3px var\(--accent-glow\);/);
assert.match(bible, /<option value="auto">🖥️ System<\/option>/);
assert.match(bible, /<option value="light">☀️ Light<\/option>/);
assert.match(bible, /<option value="dark">🌙 Dark<\/option>/);
assert.match(bible, /var themeModeSelect = document\.getElementById\('theme-mode-select'\);/);
assert.match(bible, /if \(themeModeSelect\) themeModeSelect\.value = mode;/);
assert.match(bible, /themeModeSelect\.addEventListener\('change', function \(event\) \{/);
assert.match(bible, /applyThemeMode\(themeModeSelect\.value\);/);
assert.match(bible, /applyThemeMode\(State\.getThemeMode\(\), false\);/);
assert.match(bible, /themeQuery\.addEventListener\('change', onThemeQueryChange\);/);
assert.match(bible, /themeQuery\.addListener\(function \(\) \{[\s\S]*onThemeQueryChange\(\);[\s\S]*\}\);/);
assert.match(bible, /if \(State\.getThemeMode\(\) === 'auto'\) applyThemeMode\('auto', false\);/);
assert.doesNotMatch(bible, /function nextThemeMode\(mode\)/);
assert.doesNotMatch(bible, /id="dd-dark"/);
assert.doesNotMatch(bible, /ddDarkVal/);
assert.doesNotMatch(bible, /State\.getDark\(\)/);
assert.doesNotMatch(bible, /State\.setDark/);
