const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const bible = fs.readFileSync(path.join(root, 'bible.html'), 'utf8');
const sw = fs.readFileSync(path.join(root, 'sw.js'), 'utf8');

assert.match(bible, /var APP_VERSION = '3\.0\.0';/);
assert.match(sw, /var CACHE_NAME = 'bible-v3\.0\.0';/);
assert.match(bible, /id="app-version"/);
assert.match(bible, /Version <span id="app-version">3\.0\.0<\/span>/);

assert.match(bible, /--oneui-font:/);
assert.match(bible, /--surface: #ffffff;/);
assert.match(bible, /--surface-hi: #eef3f9;/);
assert.match(bible, /--accent: #0b63ce;/);
assert.match(bible, /--accent-glow: rgba\(11,99,206,\.22\);/);
assert.match(bible, /--float-nav-bg: rgba\(255,255,255,\.64\);/);
assert.match(bible, /--float-nav-shadow: 0 8px 22px rgba\(26,40,63,\.12\);/);
assert.match(bible, /html\.dark \{[\s\S]*--surface: #171c28;/);
assert.match(bible, /html\.dark \{[\s\S]*--accent: #5b9bf4;/);
assert.match(bible, /html\.dark \{[\s\S]*--float-nav-bg: rgba\(13,16,23,\.52\);/);
assert.match(bible, /html\.dark \{[\s\S]*--float-nav-shadow: 0 8px 22px rgba\(0,0,0,\.32\);/);
assert.match(bible, /font-family: var\(--oneui-font\);/);
assert.match(bible, /backdrop-filter: var\(--hdr-blur\);/);
assert.match(bible, /background: var\(--card-bg\); border: var\(--card-border\); border-radius: var\(--radius-sm\);/);
assert.match(bible, /\.verse \{[\s\S]*border-radius: var\(--radius-sm\);[\s\S]*border: 2px solid transparent;[\s\S]*transition: background 0\.2s ease, border-color 0\.2s ease, box-shadow 0\.2s ease, padding 0\.2s ease, border-width 0\.2s ease;/);
assert.match(bible, /\.verse\.footnotes-open \{[\s\S]*border-width: 3px;[\s\S]*padding: 10px 12px;[\s\S]*background: color-mix\(in srgb, var\(--pill-bg\) 72%, transparent\);/);
assert.match(bible, /\.footnote-toggle \{[\s\S]*border-radius: var\(--radius-pill\);[\s\S]*transition: background 0\.16s ease, color 0\.16s ease, border-color 0\.16s ease, box-shadow 0\.16s ease;/);
assert.match(bible, /\.footnote-body \{[\s\S]*margin: 0 0 0 20px;[\s\S]*max-height: 0;[\s\S]*opacity: 0;[\s\S]*overflow: hidden;[\s\S]*background: var\(--note-bg\);[\s\S]*border: 0 solid color-mix\(in srgb, var\(--note-border\) 45%, transparent\);[\s\S]*border-left-width: 0;[\s\S]*border-radius: var\(--radius-sm\);[\s\S]*transition: opacity 180ms ease, max-height 220ms ease, margin 220ms ease, padding 220ms ease, border-width 220ms ease, transform 220ms ease;/);
assert.match(bible, /\.footnote-body\.visible \{[\s\S]*max-height: 40vh;[\s\S]*opacity: 1;[\s\S]*padding: 10px 12px;[\s\S]*border-width: 1px;[\s\S]*border-left-width: 4px;[\s\S]*transform: translateY\(0\);/);

assert.match(bible, /id="font-size-slider"/);
assert.match(bible, /var FONT_STEPS = \[16, 18, 20, 22, 24\];/);
assert.match(bible, /--reader-font-size/);
assert.match(bible, /bible_font_step/);
assert.match(bible, /class="font-slider-track"/);
assert.match(bible, /class="font-slider-ticks"/);
assert.match(bible, /<span style="left: 0%;">16<\/span>[\s\S]*<span style="left: 25%;">18<\/span>[\s\S]*<span style="left: 50%;">20<\/span>[\s\S]*<span style="left: 75%;">22<\/span>[\s\S]*<span style="left: 100%;">24<\/span>/);

assert.match(bible, /\.fab-panel \{[\s\S]*display: flex;[\s\S]*gap: 10px;[\s\S]*padding: 12px;[\s\S]*background: var\(--float-nav-bg\);[\s\S]*box-shadow: var\(--float-nav-shadow\);[\s\S]*backdrop-filter: blur\(28px\) saturate\(180%\);[\s\S]*-webkit-backdrop-filter: blur\(28px\) saturate\(180%\);[\s\S]*isolation: isolate;[\s\S]*transition: opacity 180ms ease, transform 180ms ease, visibility 0s linear 180ms;/);
assert.match(bible, /\.fab-panel\.open \{[\s\S]*opacity: 1;[\s\S]*visibility: visible;[\s\S]*pointer-events: auto;[\s\S]*transition: opacity 180ms ease, transform 180ms ease, visibility 0s;/);
assert.match(bible, /\.fab-panel::before \{[\s\S]*backdrop-filter: blur\(28px\) saturate\(180%\);[\s\S]*-webkit-backdrop-filter: blur\(28px\) saturate\(180%\);/);
assert.match(bible, /\.fab-card \{[\s\S]*margin: 0;[\s\S]*padding: 12px;[\s\S]*border-radius: var\(--radius-sm\);[\s\S]*background: var\(--card-bg\);[\s\S]*border: var\(--card-border\);/);
assert.match(bible, /\.fab-card-title \{[\s\S]*padding: 0 2px 8px;/);
assert.match(bible, /position: absolute;/);
assert.match(bible, /bottom: calc\(100% \+ 8px\);/);
assert.match(bible, /width: min\(360px, calc\(100vw - 24px\)\);/);
assert.match(bible, /max-height: calc\(100dvh - 96px - env\(safe-area-inset-bottom, 0px\)\);/);
assert.match(bible, /\.bottom-actions \{[\s\S]*display: flex;[\s\S]*background: var\(--float-nav-bg\);[\s\S]*backdrop-filter: var\(--hdr-blur\);/);
assert.match(bible, /\.bottom-action-button \{[\s\S]*min-height: 40px;/);
assert.match(bible, /\.bottom-history-menu \{[\s\S]*position: absolute;[\s\S]*bottom: calc\(100% \+ 8px\);[\s\S]*display: none;/);
assert.match(bible, /\.bottom-history-menu\.open \{ display: grid; \}/);
assert.match(bible, /@media \(max-width: 640px\) \{[\s\S]*\.bottom-chrome \{[\s\S]*display: grid;[\s\S]*grid-template-columns: minmax\(0, 1fr\) 48px;[\s\S]*grid-template-rows: auto auto;/);
assert.match(bible, /@media \(max-width: 640px\) \{[\s\S]*\.fab-root \{[\s\S]*grid-column: 2;[\s\S]*grid-row: 1 \/ span 2;[\s\S]*align-self: stretch;/);
assert.match(bible, /@media \(max-width: 640px\) \{[\s\S]*\.fab-main \{ height: 100%; min-height: 88px; \}/);
assert.match(bible, /<div id="auth-area" class="fab-card profile-card"><\/div>/);
assert.match(bible, /<div class="fab-card theme-mode-wrap">[\s\S]*<div class="fab-card-title">Color Scheme<\/div>/);
assert.match(bible, /<div class="fab-card font-slider-wrap">[\s\S]*<label for="font-size-slider">Text Size<\/label>/);
assert.doesNotMatch(bible, /class="fab-card history-card"/);
assert.doesNotMatch(bible, /class="fab-card search-card"/);
assert.match(bible, /<\/div>\s*<div class="bottom-actions" aria-label="Quick actions">[\s\S]*<button class="bottom-action-button" id="btn-history" type="button">[\s\S]*Recent[\s\S]*<button class="bottom-action-button" id="btn-search" type="button">[\s\S]*Search[\s\S]*<div id="history-menu" class="bottom-history-menu"/);
assert.match(bible, /\.bottom-chrome \{[\s\S]*justify-content: stretch;/);
assert.match(bible, /\.floating-nav \{[\s\S]*flex: 1 1 auto;[\s\S]*width: 100%;[\s\S]*max-width: none;/);
assert.match(bible, /\.floating-nav \{[\s\S]*box-shadow: var\(--float-nav-shadow\);/);
assert.match(bible, /\.floating-nav \.fn-chapter,\n  \.floating-nav \.fn-verse \{[\s\S]*min-width: 44px;/);
assert.doesNotMatch(bible, /\.floating-nav \.fn-chapter \{[\s\S]*min-width: 36px;/);
assert.match(bible, /\.fab-root \{[\s\S]*margin-left: auto;/);
assert.match(bible, /\.fab-main \{[\s\S]*position: relative;[\s\S]*padding: 0;[\s\S]*overflow: hidden;/);
assert.match(bible, /\.fab-main \.profile-avatar \{[\s\S]*position: absolute;[\s\S]*inset: 0;[\s\S]*width: 100%;[\s\S]*height: 100%;[\s\S]*min-width: 100%;[\s\S]*min-height: 100%;[\s\S]*max-width: none;[\s\S]*border-radius: 0;[\s\S]*object-fit: cover;[\s\S]*border: 0;/);
assert.match(bible, /\.dd-signout-button \{[\s\S]*flex-shrink: 0;[\s\S]*border-radius: var\(--radius-xs\);/);
assert.match(bible, /\.dd-sync-status \{[\s\S]*padding: 2px 0 0;/);
assert.match(bible, /details\.appendChild\(status\);/);
assert.doesNotMatch(bible, /authArea\.appendChild\(status\);/);
assert.match(bible, /<div id="floating-nav" class="floating-nav hidden" role="navigation" aria-label="Chapter">[\s\S]*<\/div>\s*<div class="bottom-actions" aria-label="Quick actions">[\s\S]*<\/div>\s*<div class="fab-root">[\s\S]*id="fab-main"/);
assert.doesNotMatch(bible, /width: 100vw;/);
assert.match(bible, /var fabPanelHistoryOpen = false;/);
assert.match(bible, /var suppressNextPopupPop = false;/);
assert.match(bible, /function currentNavStateForHistory\(\)/);
assert.match(bible, /function openFabPanel\(pushHistory\)/);
assert.match(bible, /history\.pushState\(Object\.assign\(currentNavStateForHistory\(\), \{ popup: 'menu' \}\), ''\);/);
assert.match(bible, /function closeMenus\(options\)/);
assert.match(bible, /if \(closedFab && fabPanelHistoryOpen && !options\.fromPop && !options\.keepHistory\)/);
assert.match(bible, /suppressNextPopupPop = true;[\s\S]*history\.back\(\);/);
assert.match(bible, /if \(open\) openFabPanel\(true\);/);
assert.match(bible, /else closeMenus\(\);/);
assert.doesNotMatch(bible, /height: 100dvh;/);
assert.doesNotMatch(bible, /\.fab-root:has\(\.fab-panel\.open\) \.fab-main/);
assert.doesNotMatch(bible, /id="fab-close"/);
assert.doesNotMatch(bible, /fabClose\.addEventListener\('click'/);
assert.match(bible, /outBtn\.className = 'dd-signout-button';/);
assert.match(bible, /outBtn\.textContent = 'Sign Out';/);
assert.match(bible, /info\.appendChild\(outBtn\);/);
assert.doesNotMatch(bible, /outBtn\.className = 'dd-item';/);
assert.doesNotMatch(bible, /authArea\.appendChild\(outBtn\);/);

assert.match(bible, /id="fn-verse"/);
assert.match(bible, /function showVersePickerView\(bookName, chapterNum\)/);
assert.match(bible, /view: 'verse-picker'/);
assert.match(bible, /fnVerse\.textContent = activeVerse \? activeVerse : '1';/);
assert.doesNotMatch(bible, /fnVerse\.textContent = activeVerse \? activeVerse : 'Verse';/);
assert.doesNotMatch(bible, /fnVerse\.textContent = activeVerse \? ':' \+ activeVerse : 'Verse';/);
assert.match(bible, /setActiveVerse\(keys\[0\], false\)/);
assert.match(bible, /var verseChaseFrame = null;/);
assert.match(bible, /var verseChaseVelocity = 0;/);
assert.match(bible, /var verseChaseTarget = null;/);
assert.match(bible, /var verseChaseLastTs = null;/);
assert.match(bible, /var bottomChrome = document\.getElementById\('bottom-chrome'\);/);
assert.match(bible, /function readingViewportMetrics\(\)/);
assert.match(bible, /var bottomRect = bottomChrome \? bottomChrome\.getBoundingClientRect\(\) : null;/);
assert.match(bible, /var bottomLimit = bottomRect \? Math\.min\(viewRect\.bottom, bottomRect\.top\) : viewRect\.bottom;/);
assert.match(bible, /centerY: viewRect\.top \+ \(height \/ 2\)/);
assert.match(bible, /function desiredVerseScrollTop\(target\)/);
assert.match(bible, /var metrics = readingViewportMetrics\(\);[\s\S]*var desiredTop = viewEl\.scrollTop \+ \(targetRect\.top - metrics\.top\) - \(\(metrics\.height - targetRect\.height\) \/ 2\);/);
assert.match(bible, /function shouldReduceVerseMotion\(\)/);
assert.match(bible, /function stopVerseChase\(\)/);
assert.match(bible, /function releaseVerseChaseForFreeScroll\(\)/);
assert.match(bible, /function setVerseChaseTarget\(target\)/);
assert.match(bible, /function stepVerseChase\(ts\)/);
assert.match(bible, /function scrollVerseToCenter\(target\)/);
assert.match(bible, /if \(verseChaseTarget\) return;/);
assert.match(bible, /var metrics = readingViewportMetrics\(\);[\s\S]*var centerY = metrics\.centerY;/);
assert.match(bible, /var visible = rect\.bottom > metrics\.top && rect\.top < metrics\.bottom;/);
assert.match(bible, /Math\.min\(maxTop, Math\.max\(0, desiredTop\)\)/);
assert.match(bible, /var pull = Math\.min\(0\.085, Math\.max\(0\.018, Math\.abs\(distance\) \/ 9000\)\);/);
assert.match(bible, /var damping = Math\.abs\(distance\) < 80 \? 0\.72 : 0\.88;/);
assert.match(bible, /var maxSpeed = Math\.min\(90, Math\.max\(10, Math\.abs\(distance\) \* 0\.18\)\);/);
assert.match(bible, /if \(Math\.abs\(distance\) < 0\.7 && Math\.abs\(verseChaseVelocity\) < 0\.7\)/);
assert.match(bible, /verseChaseFrame = requestAnimationFrame\(stepVerseChase\);/);
assert.match(bible, /setVerseChaseTarget\(target\);/);
assert.doesNotMatch(bible, /function verseEaseLateBrake/);
assert.doesNotMatch(bible, /var duration = Math\.min\(780/);
assert.match(bible, /\.verse-edge-spacer/);
assert.match(bible, /\.verse-head-spacer/);
assert.match(bible, /\.verse-tail-spacer/);
assert.match(bible, /headSpacer\.className = 'verse-edge-spacer verse-head-spacer';/);
assert.match(bible, /tailSpacer\.className = 'verse-edge-spacer verse-tail-spacer';/);
assert.doesNotMatch(bible, /ACTIVE_VERSE_SETTLE_MS/);
assert.doesNotMatch(bible, /activeVerseTimer/);
assert.doesNotMatch(bible, /function scheduleActiveVerseCenter/);
assert.doesNotMatch(bible, /scheduleActiveVerseCenter\(/);
assert.doesNotMatch(bible, /function isNearScrollBottom\(\)/);
assert.doesNotMatch(bible, /scrollIntoView\(\{ behavior: 'smooth', block: 'center' \}\)/);
assert.match(bible, /\.verse\.active/);

assert.match(bible, /--verse-num: #0b63ce;/);
assert.match(bible, /--verse-num: #8bb9ff;/);

assert.match(bible, /document\.addEventListener\('keydown', handleBibleKeyboardNavigation\);/);
assert.match(bible, /viewEl\.addEventListener\('wheel', releaseVerseChaseForFreeScroll, \{ passive: true \}\);/);
assert.match(bible, /viewEl\.addEventListener\('touchstart', releaseVerseChaseForFreeScroll, \{ passive: true \}\);/);
assert.match(bible, /function handleBibleKeyboardNavigation\(e\)/);
assert.match(bible, /function shouldIgnoreBibleShortcut\(e\)/);
assert.match(bible, /tag === 'INPUT' \|\| tag === 'TEXTAREA' \|\| tag === 'SELECT'/);
assert.match(bible, /e\.metaKey \|\| e\.ctrlKey \|\| e\.altKey/);
assert.match(bible, /function handleSelectionArrowKey\(key\)/);
assert.match(bible, /function focusClosestGridItem\(items, current, key\)/);
assert.match(bible, /getBoundingClientRect\(\)/);
assert.match(bible, /candidate\.score = directionalDistance\(currentRect, rect, key\);/);
assert.match(bible, /function handleSelectionEnterKey\(\)/);
assert.match(bible, /document\.activeElement\.click\(\);/);
assert.match(bible, /function handleReadingEnterKey\(\)/);
assert.match(bible, /var active = viewInner\.querySelector\('\.verse\.active'\);/);
assert.match(bible, /var noteButtons = active\.querySelectorAll\('\.footnote-toggle'\);/);
assert.match(bible, /var noteBodies = active\.querySelectorAll\('\.footnote-body'\);/);
assert.match(bible, /noteBodies\[i\]\.className = shouldOpen \? 'footnote-body visible' : 'footnote-body';/);
assert.match(bible, /noteButtons\[i\]\.className = shouldOpen \? 'footnote-toggle open' : 'footnote-toggle';/);
assert.match(bible, /active\.classList\.toggle\('footnotes-open', shouldOpen\);/);
assert.match(bible, /function syncFootnoteVerseState\(verseEl\)/);
assert.match(bible, /verseEl\.classList\.toggle\('footnotes-open', hasVisibleNote\);/);
assert.match(bible, /syncFootnoteVerseState\(bd\.parentElement\);/);
assert.match(bible, /function handleKeyboardBack\(\)/);
assert.match(bible, /if \(uiView === 'verse-picker'\) \{ showChaptersViewWithTransition\(navBook\); return true; \}/);
assert.match(bible, /if \(uiView === 'chapters'\) \{ showBooksViewWithTransition\(\); return true; \}/);
assert.match(bible, /if \(uiView === 'verses'\) \{ showVersePickerViewWithTransition\(navBook, navChapter\); return true; \}/);
assert.match(bible, /function handleReadingArrowKey\(key\)/);
assert.match(bible, /if \(key === 'ArrowLeft'\) return showAdjacentChapter\(-1\);/);
assert.match(bible, /if \(key === 'ArrowRight'\) return showAdjacentChapter\(1\);/);
assert.match(bible, /if \(key === 'ArrowUp'\) return showAdjacentVerse\(-1\);/);
assert.match(bible, /if \(key === 'ArrowDown'\) return showAdjacentVerse\(1\);/);
assert.match(bible, /function showAdjacentChapter\(direction\)/);
assert.match(bible, /direction < 0 \? prevChapterNav\(navBook, navChapter\) : nextChapterNav\(navBook, navChapter\)/);
assert.match(bible, /function showAdjacentVerse\(direction\)/);
assert.match(bible, /scrollVerseToCenter\(target\);/);
assert.match(bible, /if \(key === 'Enter'\) handled = uiView === 'verses' \? handleReadingEnterKey\(\) : handleSelectionEnterKey\(\);/);
assert.match(bible, /if \(key === 'Escape' \|\| key === 'Backspace' \|\| key === 'Delete'\) handled = handleKeyboardBack\(\);/);
assert.match(bible, /if \(suppressNextPopupPop\) \{[\s\S]*suppressNextPopupPop = false;[\s\S]*return;[\s\S]*\}/);
assert.match(bible, /if \(fabPanel\.classList\.contains\('open'\)\) \{[\s\S]*closeMenus\(\{ fromPop: true \}\);[\s\S]*return;[\s\S]*\}/);
assert.match(bible, /if \(s && s\.popup === 'menu'\) \{[\s\S]*openFabPanel\(false\);[\s\S]*return;[\s\S]*\}/);

assert.match(bible, /var CHAPTER_CROSSFADE_MS = 520;/);
assert.match(bible, /var chapterCrossfadeTimer = null;/);
assert.match(bible, /\.view-inner\.chapter-transition-retiring/);
assert.match(bible, /\.view-inner\.chapter-transition-ready \{ opacity: 0; transition: none; \}/);
assert.match(bible, /\.view-inner\.chapter-transition-ready\.chapter-transition-in \{ opacity: 1; transition: opacity 520ms ease-in-out; \}/);
assert.match(bible, /transition: opacity 520ms ease-in-out/);
assert.match(bible, /@media \(prefers-reduced-motion: reduce\) \{[\s\S]*?\.view-inner \{[\s\S]*?transition: none;/);
assert.match(bible, /function clearChapterCrossfadeTimer\(\)/);
assert.match(bible, /window\.clearTimeout\(chapterCrossfadeTimer\);/);
assert.match(bible, /function clearRetiringChapterViews\(\)/);
assert.match(bible, /viewEl\.querySelectorAll\('\.chapter-transition-retiring'\)/);
assert.match(bible, /function showVersesViewWithTransition\(bookName, chapterNum, scrollToVerse\)/);
assert.match(bible, /function showViewWithTransition\(renderView\)/);
assert.match(bible, /function showBooksViewWithTransition\(\)/);
assert.match(bible, /function showChaptersViewWithTransition\(bookName\)/);
assert.match(bible, /function showVersePickerViewWithTransition\(bookName, chapterNum\)/);
assert.match(bible, /function showSelectedVerseWithTransition\(bookName, chapterNum, verse\)/);
assert.match(bible, /function showSearchViewWithTransition\(\)/);
assert.match(bible, /var retiring = viewInner\.cloneNode\(true\);/);
assert.match(bible, /retiring\.className = 'view-inner chapter-transition-retiring';/);
assert.match(bible, /retiring\.style\.transform = 'translateY\(-' \+ viewEl\.scrollTop \+ 'px\)';/);
assert.match(bible, /viewInner\.classList\.add\('chapter-transition-ready'\);/);
assert.match(bible, /showVersesView\(bookName, chapterNum, scrollToVerse\);/);
assert.match(bible, /void viewInner\.offsetWidth;/);
assert.match(bible, /viewInner\.classList\.add\('chapter-transition-in'\);/);
assert.match(bible, /viewInner\.classList\.remove\('chapter-transition-ready', 'chapter-transition-in'\);/);
assert.match(bible, /chapterCrossfadeTimer = window\.setTimeout\(function \(\) \{/);
assert.match(bible, /showViewWithTransition\(function \(\) \{ showBooksView\(\); \}\);/);
assert.match(bible, /showViewWithTransition\(function \(\) \{ showChaptersView\(bookName\); \}\);/);
assert.match(bible, /showViewWithTransition\(function \(\) \{ showVersePickerView\(bookName, chapterNum\); \}\);/);
assert.match(bible, /showViewWithTransition\(function \(\) \{ showVersesView\(bookName, chapterNum, verse\); \}\);/);
assert.match(bible, /showViewWithTransition\(function \(\) \{ showSearchView\(\); \}\);/);
assert.match(bible, /showVersesViewWithTransition\(next\.book, next\.chapter\);/);
assert.match(bible, /if \(p\) showVersesViewWithTransition\(p\.book, p\.chapter\);/);
assert.match(bible, /if \(n\) showVersesViewWithTransition\(n\.book, n\.chapter\);/);
assert.match(bible, /showBooksViewWithTransition\(\);/);
assert.match(bible, /showChaptersViewWithTransition\(navBook\);/);
assert.match(bible, /showVersePickerViewWithTransition\(navBook, navChapter\);/);
assert.match(bible, /showSelectedVerseWithTransition\(book, ch, verse\);/);
assert.match(bible, /showSelectedVerseWithTransition\(s\.book, s\.chapter, s\.verse\);/);
assert.match(bible, /showSearchViewWithTransition\(\);/);
assert.match(bible, /document\.getElementById\('btn-history'\)\.addEventListener\('click'/);
assert.match(bible, /renderHistoryMenu\(\);[\s\S]*toggleMenu\(historyMenu, e\);/);

assert.match(bible, /getThemeMode: function \(\) \{/);
assert.match(bible, /return this\._get\('bible_theme_mode', 'light'\);/);
assert.match(bible, /setThemeMode: function \(mode\) \{/);
assert.match(bible, /mode === 'dark' \|\| mode === 'auto' \? mode : 'light'/);
assert.match(bible, /function preferredDarkQuery\(\)/);
assert.match(bible, /window\.matchMedia\('\(prefers-color-scheme: dark\)'\)/);
assert.match(bible, /function resolveThemeMode\(mode\)/);
assert.match(bible, /if \(mode !== 'auto'\) return mode === 'dark';/);
assert.match(bible, /return preferredDarkQuery\(\) \? preferredDarkQuery\(\)\.matches : false;/);
assert.match(bible, /function applyThemeMode\(mode\)/);
assert.match(bible, /State\.setThemeMode\(mode\);/);
assert.match(bible, /document\.documentElement\.classList\.toggle\('dark', resolveThemeMode\(mode\)\);/);
assert.match(bible, /class="fab-card theme-mode-wrap"/);
assert.match(bible, /class="theme-mode-control" role="group" aria-label="Color scheme"/);
assert.match(bible, /data-theme-mode="light" aria-pressed="true">Light<\/button>/);
assert.match(bible, /data-theme-mode="dark" aria-pressed="false">Dark<\/button>/);
assert.match(bible, /data-theme-mode="auto" aria-pressed="false">Auto<\/button>/);
assert.match(bible, /var themeModeButtons = Array\.prototype\.slice\.call\(document\.querySelectorAll\('\[data-theme-mode\]'\)\);/);
assert.match(bible, /button\.classList\.toggle\('active', selected\);/);
assert.match(bible, /button\.setAttribute\('aria-pressed', selected \? 'true' : 'false'\);/);
assert.match(bible, /themeModeButtons\.forEach\(function \(button\) \{/);
assert.match(bible, /applyThemeMode\(button\.getAttribute\('data-theme-mode'\)\);/);
assert.match(bible, /applyThemeMode\(State\.getThemeMode\(\)\);/);
assert.match(bible, /themeQuery\.addEventListener\('change', onThemeQueryChange\);/);
assert.match(bible, /themeQuery\.addListener\(function \(\) \{/);
assert.match(bible, /if \(State\.getThemeMode\(\) === 'auto'\) applyThemeMode\('auto'\);/);
assert.doesNotMatch(bible, /function nextThemeMode\(mode\)/);
assert.doesNotMatch(bible, /id="dd-dark"/);
assert.doesNotMatch(bible, /ddDarkVal/);
assert.doesNotMatch(bible, /State\.getDark\(\)/);
assert.doesNotMatch(bible, /State\.setDark/);
